SYNC_INTERVAL = 60
TIMEZONE = 'Asia/Manila'
LOG_FILE = '../logs/sync.log'
STATE_FILE = '../state/db_state.json'

#DO NOT UNDER ANY CIRCUMSTANCES REASSIGN VALUES TO THESE VARIABLES OR ELSE I WILL BEAT YOU TO DEATH